Repository SPARTA42CLUB/Webserver, pull requests merged in 2024-06, with the labels that each got.

#2 Feature/#1 parsing config
  .github/workflows/maketest.yml
  Makefile
  config/server.conf
  inc/Config.hpp
  inc/Server.hpp
  inc/error.hpp
  src/Config.cpp
  src/Server.cpp
  src/error.cpp
  src/main.cpp
Labels: enhancement

#4 Doc: 코드 설명 주석 추가
  Makefile
  inc/HttpResponse.hpp
  inc/Server.hpp
  src/Config.cpp
  src/HttpResponse.cpp
  src/Server.cpp
  src/error.cpp
  src/main.cpp
Labels: documentation, enhancement

#11 Feature/#5 basic server
  Makefile
  default.conf
  inc/Server.hpp
  obj/.gitkeep
  src/Server.cpp
  src/client/Client.cpp
  src/client/Client.hpp
  src/eventManager/EventManager.cpp
  src/eventManager/EventManager.hpp
  src/global/config/Config.cpp
  src/global/config/Config.hpp
  src/global/error/error.cpp
  src/global/error/error.hpp
  src/httpRequest/HttpRequest.cpp
  src/httpRequest/HttpRequest.hpp
  src/httpResponse/HttpResponse.cpp
  src/httpResponse/HttpResponse.hpp
  src/main.cpp
  src/requestHandler/RequestHandler.cpp
  src/requestHandler/RequestHandler.hpp
  src/server/Server.cpp
  src/server/Server.hpp
Labels: enhancement, feature

#16 Refactoring/#13 delete Client
  src/client/Client.cpp
  src/client/Client.hpp
  src/server/Server.cpp
  src/server/Server.hpp
Labels: enhancement

#37 Feature/#26 persistent connection
  default.conf
  src/eventManager/EventManager.cpp
  src/global/config/Config.cpp
  src/global/config/Config.hpp
  src/httpMessage/headerFields/HeaderFields.cpp
  src/server/Server.cpp
  src/server/Server.hpp
Labels: enhancement, feature

#50 Feature/#49 read event
  src/httpMessage/headerFields/HeaderFields.hpp
  src/requestHandler/RequestHandler.cpp
  src/server/Server.cpp
  src/server/Server.hpp
  test/webservRequestTester/tester.sh
Labels: enhancement, feature

#60 Feature/#27 check chunked
  .gitignore
  src/server/Server.cpp
  src/server/Server.hpp
  test/webservRequestTester/chunk_tester.cpp
  test/webservRequestTester/chunked_test
  test/webservRequestTester/test.conf
Labels: enhancement, feature

#61 [Feat]: chunke 요청에 대한 처리
  src/requestHandler/chunkedRequestReader/ChunkedRequestReader.cpp
  src/requestHandler/chunkedRequestReader/ChunkedRequestReader.hpp
  src/server/Server.cpp
  upload/chunk.py
  upload/testImage.png
  upload/testfile.png
Labels: enhancement

#62 [Feat]: 206 Partial Content 기능 추가
  src/requestHandler/RequestHandler.cpp
  src/requestHandler/RequestHandler.hpp
  src/requestHandler/rangeRequestReader/RangeRequestReader.cpp
  src/requestHandler/rangeRequestReader/RangeRequestReader.hpp
Labels: enhancement, feature

#68 [Fix] Allow Methods 파싱에서 마지막 메서드를 빼고 저장하는 버그 수정
  src/global/config/Config.cpp
Labels: bug

#71 Refactoring/#17 connection class
  Makefile
  src/Connection/Connection.cpp
  src/Connection/Connection.hpp
  src/eventManager/EventManager.cpp
  src/eventManager/EventManager.hpp
  src/global/Logger/Logger.cpp
  src/global/Logger/Logger.hpp
  src/global/config/Config.cpp
  src/global/config/Config.hpp
  src/global/exception/ConfigException.cpp
  src/global/exception/ConfigException.hpp
  src/global/exception/Exception.cpp
  src/global/exception/Exception.hpp
  src/global/exception/SocketException.cpp
  src/global/exception/SocketException.hpp
  src/httpMessage/RequestMessage.cpp
  src/httpMessage/RequestMessage.hpp
  src/main.cpp
  src/requestHandler/RequestHandler.cpp
  src/requestHandler/RequestHandler.hpp
  src/server/Server.cpp
  src/server/Server.hpp
  upload/testfile.png
Labels: enhancement, feature

#73 Refactoring/#17 connection class
  src/connection/Connection.cpp
  src/connection/Connection.hpp
  src/global/config/Config.cpp
  src/global/config/Config.hpp
  src/global/logger/Logger.cpp
  src/server/Server.cpp
  src/server/Server.hpp
Labels: enhancement

#76 Refactoring/request handler logic
  Makefile
  src/config/serverConfig/ServerConfig.cpp
  src/global/exception/HTTPException.cpp
  src/global/exception/HTTPException.hpp
  src/global/logger/Logger.cpp
  src/global/logger/Logger.hpp
  src/httpMessage/HttpStatusCode.hpp
  src/httpMessage/RequestMessage.cpp
  src/httpMessage/RequestMessage.hpp
  src/httpMessage/headerFields/HeaderFields.cpp
  src/httpMessage/startLine/StartLine.cpp
  src/main.cpp
  src/requestHandler/RequestHandler.cpp
  src/requestHandler/RequestHandler.hpp
  src/server/Server.cpp
  src/server/Server.hpp
  src/server/connection/Connection.cpp
  src/server/connection/Connection.hpp
  test/webservRequestTester/chunk_tester.cpp
  test/webservRequestTester/chunked_test
  test/webservRequestTester/test.conf
  test/webservRequestTester/tester.sh
  www/delete
Labels: enhancement, feature

#77 [Feat] 버그 수정 및 Post 기능 구현
  src/server/Server.cpp
  src/server/Server.hpp
  www/favicon.ico
Labels: bug, feature

#86 Feature/#63 client max body
  conf/default.conf
  src/config/Config.hpp
  src/config/serverConfig/ServerConfig.cpp
  src/config/serverConfig/ServerConfig.hpp
  src/global/eventManager/EventManager.cpp
  src/global/eventManager/EventManager.hpp
  src/global/exception/SysException.cpp
  src/global/exception/SysException.hpp
  src/global/logger/Logger.cpp
  src/global/logger/Logger.hpp
  src/httpMessage/RequestMessage.cpp
  src/httpMessage/RequestMessage.hpp
  src/httpMessage/ResponseMessage.cpp
  src/httpMessage/ResponseMessage.hpp
  src/httpMessage/startLine/StartLine.cpp
  src/httpMessage/startLine/StartLine.hpp
  src/main.cpp
  src/requestHandler/CgiRequestHandler/CgiRequestHandler.cpp
  src/requestHandler/CgiRequestHandler/CgiRequestHandler.hpp
  src/requestHandler/RequestHandler.cpp
  src/requestHandler/RequestHandler.hpp
  src/server/Server.cpp
  src/server/Server.hpp
  src/server/connection/Connection.cpp
  src/server/connection/Connection.hpp
  test/checkLeak/leak.sh
  test/webservRequestTester/READMD.md
  test/webservRequestTester/test.conf
  test/webservRequestTester/tester.sh
  www/cat.jpeg
  www/cgi-bin/index.py
  www/delete
  www/error/404.html
  www/error/50x.html
  www/favicon.ico
  www/index.html
  www/pages/depth1/depth1.html
  www/pages/depth1/depth2/depth2.html
  www/pages/page.html
  www/pages/redirect.html
  www/pages/server1
  www/pages/server2
  www/pages/server3
  www/script/script.js
  www/style/reset.css
  www/style/style.css
  www/upload/haha.txt
  www/upload/hello.html
  www/upload/test.png
Labels: enhancement, feature

#90 Feature/changing config policy
  src/config/Config.cpp
  src/config/Config.hpp
  src/requestHandler/CgiRequestHandler/CgiRequestHandler.cpp
  src/requestHandler/CgiRequestHandler/CgiRequestHandler.hpp
  src/requestHandler/RequestHandler.cpp
  src/requestHandler/RequestHandler.hpp
  src/server/Server.cpp
  src/server/Server.hpp
  src/server/connection/Connection.cpp
  src/server/connection/Connection.hpp
Labels: enhancement

#92 feature: HEAD 요청에 대한 에러페이지 응답 처리
  src/global/logger/Logger.cpp
  src/global/logger/Logger.hpp
  src/httpMessage/ResponseMessage.hpp
  src/server/Server.cpp
Labels: enhancement

#94 Bug fix/crazy connection close header
  conf/default.conf
  src/requestHandler/RequestHandler.cpp
  src/server/Server.cpp
  src/server/connection/Connection.cpp
  src/server/connection/Connection.hpp
  test/webservRequestTester/tester.sh
Labels: bug, enhancement
